# fly.toml app configuration file generated for reverse-image-search on 2026-06-19T18:21:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reverse-image-search'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'selfwatch_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
